/**
 * Copyright (c) 2020, Self XDSD Contributors
 * All rights reserved.
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to read the Software only. Permission is hereby NOT GRANTED to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software.
 * <p>
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package com.selfxdsd.todocli;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Todo Parser.
 * @version $Id$
 * @since 0.0.1
 */
public final class TodoParser {

    /**
     * TODO Markers.
     */
    private static final String MARKERS = "@todo|TODO|@fixme|FIXME";

    /**
     * Regex used for matching a single-line comment.
     */
    private final String singleLineRegex;


    /**
     * Regex used for matching a multi-line comment.
     */
    private final String multiLineRegex;

    /**
     * Pattern used for matching the body of a TODO in a multi-line comment.
     */
    private final Pattern multiLinePattern;

    /**
     * Creates a new TodoParser object.
     */
    public TodoParser() {
        this.singleLineRegex = "^(\\s*//\\s*)(" + MARKERS + ").*$";
        this.multiLineRegex = "^(\\s*[*]\\s*)(" + MARKERS + ").*$";
        this.multiLinePattern = Pattern.compile("(\\s*[*])(\\s\\s)(.*)");
    }

    /**
     * Finds and returns a list of all TODOs found in the file given its path.
     * @param path Path to the file being parsed.
     * @return List of found TODOs.
     * @throws IOException If something goes wrong.
     * @checkstyle ExecutableStatementCount (50 lines)
     */
    public List<Todo> parse(final String path) throws IOException {
        List<String> lines = Files.readAllLines(Paths.get(path));
        List<Todo> todos = new ArrayList<>();
        final AtomicInteger currentIndex = new AtomicInteger(-1);

        while (currentIndex.incrementAndGet() < lines.size()) {
            String line = lines.get(currentIndex.get());

            int headerIndex = getHeaderIndex(line);
            if (headerIndex == -1) {
                continue;
            }

            final String[] parts = line.substring(headerIndex)
                .trim().split("\\s", 2);
            if (parts[0].isEmpty() || !parts[0]
                .matches("#\\d+:\\d+(m|min|mins)\\b")){
                continue;
            }

            final String header = parts[0].trim();
            final String body;
            if (parts.length == 2) {
                body = parts[1].trim();
            } else {
                body = "";
            }

            if(!body.trim().startsWith("Autogenerated")) {
                Todo todo;
                if (line.matches(this.singleLineRegex)) {
                    todo = new Todo(
                        currentIndex.get() + 1,
                        currentIndex.get() + 1,
                        body
                    );
                } else if (line.matches(this.multiLineRegex)) {
                    todo = parseMultiLineTodo(lines, body, currentIndex);
                } else {
                    continue;
                }
                if(!todo.getBody().isBlank()) {
                    setRemainingTodoFields(todo, header, path);
                    todos.add(todo);
                }
            }
        }
        return todos;
    }

    /**
     * Parses multiple lines of the input file and extracts the TODO object.
     * @param lines Lines of the multi-line TODO.
     * @param body The TODO's body; could be empty
     * @param currentIndex Index of the currently parsed line.
     * @return The extracted TODO object
     */
    private Todo parseMultiLineTodo(
        final List<String> lines,
        final String body,
        final AtomicInteger currentIndex
    ) {
        int start = currentIndex.get() + 1;
        StringBuilder bodyBuilder = new StringBuilder(body);
        while (true) {
            String line = lines.get(currentIndex.incrementAndGet());
            Matcher matcher = this.multiLinePattern.matcher(line);
            if (matcher.find()) {
                String bodyContinuation = matcher.group(3);

                if (bodyBuilder.length() > 0) {
                    bodyBuilder.append(" ");
                }
                bodyBuilder.append(bodyContinuation);

            } else {
                currentIndex.decrementAndGet();
                break;
            }
        }
        return new Todo(start, currentIndex.get() + 1, bodyBuilder.toString());
    }

    /**
     * Sets the remaining TODO fields: ticket ID, estimated time, and path.
     * @param todo The TODO object to update.
     * @param header The header, containing ticket ID and estimated time.
     * @param path The path of the file in which the TODO was found.
     */
    private void setRemainingTodoFields(
        final Todo todo,
        final String header,
        final String path
    ) {
        final String[] parts = header.split(":");

        todo.setTicketID(parts[0]);
        todo.setEstimatedTime(
            Integer.parseInt(
                parts[1].replaceAll("[A-Za-z]+", "")
            )
        );
        todo.setPath(path);
    }

    /**
     * Checks if a TODO is present in the given line and if so, returns
     * the index of its header, i.e. of the header's first character.
     * Header consists of the ticker number and the estimated time.
     *
     * @param line The source code line to check
     * @return Index of header or -1 if the line contains no TODO
     */
    private int getHeaderIndex(final String line) {
        int index = -1;
        for (final String todo : MARKERS.split("\\|")) {
            int todoIndex = line.indexOf(todo);
            if (todoIndex != -1) {
                index = todoIndex + todo.length();
                break;
            }
        }
        return index;
    }

}